server:
  port: 8080
  servlet:
    context-path: /demo1

spring:
  datasource:
    url: ${DBMS_CONNECTION:jdbc:mysql://localhost:3306/demo_web}
    driverClassName: "com.mysql.cj.jdbc.Driver"
    username: ${DBMS_USERNAME:root}
    password: ${DBMS_PASSWORD:root}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

jwt:
  signerKey: "UM0WtBMa5k65DJ+2A29U4qELZ9yRSiBHWLSsQ/xJMXMJ83NeYA04cliMmZuS51qA\n"
  valid-duration: 3600 # in seconds
  refreshable-duration: 36000 # in seconds

dbname: "demo_web"